### ISSUE TITLE
posso usar seu codigo?

### ISSUE THREAD

**Issue by lucasnuic** [tomas-barros1/JS-Digital-Bank#1]
estou criando um jogo de memoria chamado wubbalubba que é homenagem ao desenho ricky and morty. mas tem várias fases e é bem complexo. posso usar seu codigo? estou criando um mini banco para ter pontuacao do jogo.

**Comment by tomas-barros1** [comment]
pode, sem problemas

**Comment by lucasnuic** [comment]
Oi @tomas-barros1, poderia adicionar uma licença nele? (é que o github pode me processar ou remover meus repositórios de código aberto, em teoria tudo tem que ter direito de código senão é processo)

e mais uma coisa mano, posso te seguir? acho teus repos, muito daora.
