### ISSUE TITLE
filename

### ISSUE THREAD

**Issue by ghost** [tomas-barros1/JS-Digital-Bank#5]

**Comment by tomas-barros1** [comment]
Você que sabe kkkk, esse repositório foi de um exercício de POO de uma plataforma de ensino que eu assino.

**Comment by tomas-barros1** [comment]
Eu assino a OneBitCode, se seu intuito for se tornar um dev full stack eu recomendo. Eu aprendi poo no curso técnico que eu faço em java, tem uma série bem legal de vídeos do Gustavo Guanabara ensinando poo em java e php (grátis no youtube), lá na one bit eles ensinam tudo em java script, só que é pago. Se quiser trocar uma ideia me adiciona no Discord tomzay.

**Comment by tomas-barros1** [comment]
beleza!

**Comment by tomas-barros1** [comment]
quem aprende c e pascal aprende qualquer coisa kkkk, tamo junto
